// Embedded movie data to avoid CORS issues
const MOVIE_DATA = [
    {Name: "The Dark Knight", Year: "2008", Genre: "Action", Rating: "PG-13", BoxOffice: "1005.0", Budget: "185", Director: "Christopher Nolan", Country: "USA", Runtime: "152", IMDB_Score: "9.0"},
    {Name: "Inception", Year: "2010", Genre: "Sci-Fi", Rating: "PG-13", BoxOffice: "836.8", Budget: "160", Director: "Christopher Nolan", Country: "USA", Runtime: "148", IMDB_Score: "8.8"},
    {Name: "Interstellar", Year: "2014", Genre: "Sci-Fi", Rating: "PG-13", BoxOffice: "677.5", Budget: "165", Director: "Christopher Nolan", Country: "USA", Runtime: "169", IMDB_Score: "8.6"},
    {Name: "The Matrix", Year: "1999", Genre: "Sci-Fi", Rating: "R", BoxOffice: "467.2", Budget: "63", Director: "The Wachowskis", Country: "USA", Runtime: "136", IMDB_Score: "8.7"},
    {Name: "Pulp Fiction", Year: "1994", Genre: "Crime", Rating: "R", BoxOffice: "214.2", Budget: "8", Director: "Quentin Tarantino", Country: "USA", Runtime: "154", IMDB_Score: "8.9"},
    {Name: "Forrest Gump", Year: "1994", Genre: "Drama", Rating: "PG-13", BoxOffice: "677.9", Budget: "55", Director: "Robert Zemeckis", Country: "USA", Runtime: "142", IMDB_Score: "8.8"},
    {Name: "The Shawshank Redemption", Year: "1994", Genre: "Drama", Rating: "R", BoxOffice: "58.4", Budget: "25", Director: "Frank Darabont", Country: "USA", Runtime: "142", IMDB_Score: "9.3"},
    {Name: "Titanic", Year: "1997", Genre: "Drama", Rating: "PG-13", BoxOffice: "2201.6", Budget: "200", Director: "James Cameron", Country: "USA", Runtime: "194", IMDB_Score: "7.8"},
    {Name: "Avatar", Year: "2009", Genre: "Sci-Fi", Rating: "PG-13", BoxOffice: "2787.9", Budget: "237", Director: "James Cameron", Country: "USA", Runtime: "162", IMDB_Score: "7.8"},
    {Name: "Jurassic Park", Year: "1993", Genre: "Adventure", Rating: "PG-13", BoxOffice: "1030.0", Budget: "63", Director: "Steven Spielberg", Country: "USA", Runtime: "127", IMDB_Score: "8.1"},
    {Name: "E.T.", Year: "1982", Genre: "Sci-Fi", Rating: "PG", BoxOffice: "792.9", Budget: "10.5", Director: "Steven Spielberg", Country: "USA", Runtime: "115", IMDB_Score: "7.8"},
    {Name: "Jaws", Year: "1975", Genre: "Thriller", Rating: "PG", BoxOffice: "470.7", Budget: "9", Director: "Steven Spielberg", Country: "USA", Runtime: "124", IMDB_Score: "8.0"},
    {Name: "Star Wars", Year: "1977", Genre: "Sci-Fi", Rating: "PG", BoxOffice: "775.4", Budget: "11", Director: "George Lucas", Country: "USA", Runtime: "121", IMDB_Score: "8.6"},
    {Name: "The Godfather", Year: "1972", Genre: "Crime", Rating: "R", BoxOffice: "287.0", Budget: "6", Director: "Francis Ford Coppola", Country: "USA", Runtime: "175", IMDB_Score: "9.2"},
    {Name: "Casablanca", Year: "1942", Genre: "Drama", Rating: "PG", BoxOffice: "1.0", Budget: "1.0", Director: "Michael Curtiz", Country: "USA", Runtime: "102", IMDB_Score: "8.5"},
    {Name: "The Avengers", Year: "2012", Genre: "Action", Rating: "PG-13", BoxOffice: "1518.8", Budget: "220", Director: "Joss Whedon", Country: "USA", Runtime: "143", IMDB_Score: "8.0"},
    {Name: "Black Panther", Year: "2018", Genre: "Action", Rating: "PG-13", BoxOffice: "1347.0", Budget: "200", Director: "Ryan Coogler", Country: "USA", Runtime: "134", IMDB_Score: "7.3"},
    {Name: "Wonder Woman", Year: "2017", Genre: "Action", Rating: "PG-13", BoxOffice: "821.8", Budget: "149", Director: "Patty Jenkins", Country: "USA", Runtime: "141", IMDB_Score: "7.4"},
    {Name: "Mad Max: Fury Road", Year: "2015", Genre: "Action", Rating: "R", BoxOffice: "378.4", Budget: "150", Director: "George Miller", Country: "Australia", Runtime: "120", IMDB_Score: "8.1"},
    {Name: "The Lion King", Year: "1994", Genre: "Animation", Rating: "G", BoxOffice: "968.5", Budget: "45", Director: "Roger Allers", Country: "USA", Runtime: "88", IMDB_Score: "8.5"},
    {Name: "Toy Story", Year: "1995", Genre: "Animation", Rating: "G", BoxOffice: "373.6", Budget: "30", Director: "John Lasseter", Country: "USA", Runtime: "81", IMDB_Score: "8.3"},
    {Name: "Finding Nemo", Year: "2003", Genre: "Animation", Rating: "G", BoxOffice: "940.3", Budget: "94", Director: "Andrew Stanton", Country: "USA", Runtime: "100", IMDB_Score: "8.2"},
    {Name: "Up", Year: "2009", Genre: "Animation", Rating: "PG", BoxOffice: "735.1", Budget: "175", Director: "Pete Docter", Country: "USA", Runtime: "96", IMDB_Score: "8.2"},
    {Name: "The Incredibles", Year: "2004", Genre: "Animation", Rating: "PG", BoxOffice: "631.4", Budget: "92", Director: "Brad Bird", Country: "USA", Runtime: "115", IMDB_Score: "8.0"},
    {Name: "Frozen", Year: "2013", Genre: "Animation", Rating: "PG", BoxOffice: "1280.0", Budget: "150", Director: "Chris Buck", Country: "USA", Runtime: "102", IMDB_Score: "7.4"},
    {Name: "The Hangover", Year: "2009", Genre: "Comedy", Rating: "R", BoxOffice: "467.5", Budget: "35", Director: "Todd Phillips", Country: "USA", Runtime: "100", IMDB_Score: "7.7"},
    {Name: "Bridesmaids", Year: "2011", Genre: "Comedy", Rating: "R", BoxOffice: "288.4", Budget: "32.5", Director: "Paul Feig", Country: "USA", Runtime: "125", IMDB_Score: "6.8"},
    {Name: "Superbad", Year: "2007", Genre: "Comedy", Rating: "R", BoxOffice: "169.9", Budget: "20", Director: "Greg Mottola", Country: "USA", Runtime: "113", IMDB_Score: "7.6"},
    {Name: "The Exorcist", Year: "1973", Genre: "Horror", Rating: "R", BoxOffice: "441.3", Budget: "12", Director: "William Friedkin", Country: "USA", Runtime: "122", IMDB_Score: "8.0"},
    {Name: "Get Out", Year: "2017", Genre: "Horror", Rating: "R", BoxOffice: "255.4", Budget: "4.5", Director: "Jordan Peele", Country: "USA", Runtime: "104", IMDB_Score: "7.7"},
    {Name: "The Conjuring", Year: "2013", Genre: "Horror", Rating: "R", BoxOffice: "319.5", Budget: "20", Director: "James Wan", Country: "USA", Runtime: "112", IMDB_Score: "7.5"},
    {Name: "A Quiet Place", Year: "2018", Genre: "Horror", Rating: "PG-13", BoxOffice: "340.9", Budget: "17", Director: "John Krasinski", Country: "USA", Runtime: "90", IMDB_Score: "7.5"},
    {Name: "The Sixth Sense", Year: "1999", Genre: "Horror", Rating: "PG-13", BoxOffice: "672.8", Budget: "40", Director: "M. Night Shyamalan", Country: "USA", Runtime: "107", IMDB_Score: "8.1"},
    {Name: "Gladiator", Year: "2000", Genre: "Action", Rating: "R", BoxOffice: "503.2", Budget: "103", Director: "Ridley Scott", Country: "USA", Runtime: "155", IMDB_Score: "8.5"},
    {Name: "Saving Private Ryan", Year: "1998", Genre: "War", Rating: "R", BoxOffice: "481.8", Budget: "70", Director: "Steven Spielberg", Country: "USA", Runtime: "169", IMDB_Score: "8.6"},
    {Name: "Schindler's List", Year: "1993", Genre: "War", Rating: "R", BoxOffice: "321.2", Budget: "22", Director: "Steven Spielberg", Country: "USA", Runtime: "195", IMDB_Score: "8.9"},
    {Name: "Apocalypse Now", Year: "1979", Genre: "War", Rating: "R", BoxOffice: "150.0", Budget: "31", Director: "Francis Ford Coppola", Country: "USA", Runtime: "147", IMDB_Score: "8.4"},
    {Name: "The Lord of the Rings: Fellowship", Year: "2001", Genre: "Fantasy", Rating: "PG-13", BoxOffice: "871.5", Budget: "93", Director: "Peter Jackson", Country: "New Zealand", Runtime: "178", IMDB_Score: "8.8"},
    {Name: "Harry Potter and the Sorcerer's Stone", Year: "2001", Genre: "Fantasy", Rating: "PG", BoxOffice: "974.8", Budget: "125", Director: "Chris Columbus", Country: "UK", Runtime: "152", IMDB_Score: "7.6"},
    {Name: "The Wizard of Oz", Year: "1939", Genre: "Fantasy", Rating: "G", BoxOffice: "3.0", Budget: "2.8", Director: "Victor Fleming", Country: "USA", Runtime: "102", IMDB_Score: "8.0"},
    {Name: "The Social Network", Year: "2010", Genre: "Drama", Rating: "PG-13", BoxOffice: "224.9", Budget: "40", Director: "David Fincher", Country: "USA", Runtime: "120", IMDB_Score: "7.7"},
    {Name: "Goodfellas", Year: "1990", Genre: "Crime", Rating: "R", BoxOffice: "46.8", Budget: "25", Director: "Martin Scorsese", Country: "USA", Runtime: "146", IMDB_Score: "8.7"},
    {Name: "The Departed", Year: "2006", Genre: "Crime", Rating: "R", BoxOffice: "291.5", Budget: "90", Director: "Martin Scorsese", Country: "USA", Runtime: "151", IMDB_Score: "8.5"},
    {Name: "Fight Club", Year: "1999", Genre: "Crime", Rating: "R", BoxOffice: "100.9", Budget: "63", Director: "David Fincher", Country: "USA", Runtime: "139", IMDB_Score: "8.8"},
    {Name: "Guardians of the Galaxy", Year: "2014", Genre: "Action", Rating: "PG-13", BoxOffice: "773.3", Budget: "170", Director: "James Gunn", Country: "USA", Runtime: "121", IMDB_Score: "8.0"},
    {Name: "Iron Man", Year: "2008", Genre: "Action", Rating: "PG-13", BoxOffice: "585.2", Budget: "140", Director: "Jon Favreau", Country: "USA", Runtime: "126", IMDB_Score: "7.9"},
    {Name: "Spider-Man", Year: "2002", Genre: "Action", Rating: "PG-13", BoxOffice: "821.7", Budget: "139", Director: "Sam Raimi", Country: "USA", Runtime: "121", IMDB_Score: "7.4"},
    {Name: "The Dark Knight Rises", Year: "2012", Genre: "Action", Rating: "PG-13", BoxOffice: "1084.9", Budget: "250", Director: "Christopher Nolan", Country: "USA", Runtime: "164", IMDB_Score: "8.4"},
    {Name: "Batman Begins", Year: "2005", Genre: "Action", Rating: "PG-13", BoxOffice: "374.2", Budget: "150", Director: "Christopher Nolan", Country: "USA", Runtime: "140", IMDB_Score: "8.2"},
    {Name: "Dunkirk", Year: "2017", Genre: "War", Rating: "PG-13", BoxOffice: "526.0", Budget: "100", Director: "Christopher Nolan", Country: "UK", Runtime: "106", IMDB_Score: "7.8"},
    {Name: "Gravity", Year: "2013", Genre: "Sci-Fi", Rating: "PG-13", BoxOffice: "723.2", Budget: "100", Director: "Alfonso Cuaron", Country: "USA", Runtime: "91", IMDB_Score: "7.7"},
    {Name: "Blade Runner 2049", Year: "2017", Genre: "Sci-Fi", Rating: "R", BoxOffice: "259.2", Budget: "150", Director: "Denis Villeneuve", Country: "USA", Runtime: "164", IMDB_Score: "8.0"},
    {Name: "Arrival", Year: "2016", Genre: "Sci-Fi", Rating: "PG-13", BoxOffice: "203.4", Budget: "47", Director: "Denis Villeneuve", Country: "USA", Runtime: "116", IMDB_Score: "7.9"},
    {Name: "The Martian", Year: "2015", Genre: "Sci-Fi", Rating: "PG-13", BoxOffice: "630.2", Budget: "108", Director: "Ridley Scott", Country: "USA", Runtime: "144", IMDB_Score: "8.0"},
    {Name: "La La Land", Year: "2016", Genre: "Musical", Rating: "PG-13", BoxOffice: "446.1", Budget: "30", Director: "Damien Chazelle", Country: "USA", Runtime: "128", IMDB_Score: "8.0"},
    {Name: "The Greatest Showman", Year: "2017", Genre: "Musical", Rating: "PG", BoxOffice: "434.9", Budget: "84", Director: "Michael Gracey", Country: "USA", Runtime: "105", IMDB_Score: "7.6"},
    {Name: "Mamma Mia!", Year: "2008", Genre: "Musical", Rating: "PG-13", BoxOffice: "609.8", Budget: "52", Director: "Phyllida Lloyd", Country: "UK", Runtime: "108", IMDB_Score: "6.4"},
    {Name: "Chicago", Year: "2002", Genre: "Musical", Rating: "PG-13", BoxOffice: "306.8", Budget: "45", Director: "Rob Marshall", Country: "USA", Runtime: "113", IMDB_Score: "7.1"},
    {Name: "The Sound of Music", Year: "1965", Genre: "Musical", Rating: "G", BoxOffice: "286.2", Budget: "8.2", Director: "Robert Wise", Country: "USA", Runtime: "174", IMDB_Score: "8.0"}
];

